name: MinebotXPBank
main: net.minebot.xpbank.MinebotXPBank
version: 0.2
commands:
    xpbank:
        description: xpbank command
        permission: xpbank.use
        usage: |
            /xpbank help
permissions:
    xpbank.use:
        description: Allows use of /xpbank
        default: op